[project]
name = "gebietsstammdaten-zh"
version = "0.1.0"
description = "Zentrale Referenz fÃ¼r konsistente, qualitÃ¤tsgesicherte Gebietsangaben, die in kantonalen Prozessen verwendet werden."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
]

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/gebietsstammdaten"]
